### ISSUE TITLE
Pipeline import from REW failure

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#115]
Hello Henrik,

could you share some insight about the format questions regarding type fields etc.? Please take a look here:
https://www.avnirvana.com/threads/camilladsp-iir-format-output.11060/page-2
What I get importing this is (from REW beta 39):
[C_TT_RTA_3_Mic_FR.yml.zip](https://github.com/user-attachments/files/16069226/C_TT_RTA_3_Mic_FR.yml.zip)
First it looks ok in the web gui:
![image](https://github.com/HEnquist/camillagui/assets/55871370/c0efa454-37d7-4c21-9145-93aa96666dd8)
But then there is this red error triangle with (excl. mark) at the pipeline tab and this tab is empty. Browser reload brings pipeline view back but filters and its group were not added.
![image](https://github.com/HEnquist/camillagui/assets/55871370/7772d01a-73e5-4b4b-8bf9-54298b51d2c1)
Just importing filters without its pipeline group works btw.

**Comment by mike811** [comment]
This works:
![image](https://github.com/HEnquist/camillagui/assets/55871370/903d75c8-cc24-4497-b9bf-27e348775eb7)
So it seems "- names" was wrong.

**Comment by HEnquist** [comment]
`pipeline` is supposed to be a list of objects (with each object representing a pipeline step), but in the previous REW export `pipeline` is just a single object instead of a list. It also lacks the `channel` property. The import function of the gui has a little bit of extra logic to handle these files. If the REW output has changed, then this may need an update. The easiest would be if REW exported a completely valid pipeline section so that nothing extra needs to be done.

**Comment by mike811** [comment]
Hello Henrik,

John implemented a complete pipeline section with channel property. It is working fine here. Maybe you could change the pipeline 0 stuff from the import window and display the channel number from the section?

Regards
Michael

**Comment by HEnquist** [comment]
Great, this simplifies things! 
The pipeline 0 thing has to stay, the same logic handles import of all camilladsp config files where there may be many steps, and more than one step may filter any given channel. The channel number should be shown in the tooltip.
