### ISSUE TITLE
Gui doesn't show correct version of camilladsp when offline

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camillagui#47]
Minor issue; when opening the editor while camilladsp hasn't been online mode no camilladsp version is shown. Just a tripple x version:

![image](https://user-images.githubusercontent.com/1525169/119035991-857ee280-b9b0-11eb-835f-514b276e606f.png)

Once you have been `online` the correct version is shown, even if you go back to offline mode.

**Comment by bitkeeper** [comment]
I see that the offline (_with setting backup_camilla_path_) isn't used anymore, so that can also not be a source of the version.
Would it be an option to just call `camilladsp --version` (from the setting `backup_camilla_path settin`g) from the backend to capture the version? 
If not just feel free to close the issue, because it a very minor one :-)

Supporting case:
It would ease support, because when you have a problem and camilladsp will not start, you will have no way to the see the current camilladsp version, without forcing the user to the commandline.

**Comment by HEnquist** [comment]
Yes the backup camilladsp instance was removed since we don't need it for config validation any more. That would then need to be added back.
I see the point for support, but my feeling is that this could generate more trouble than it prevents. The user then must configure the path to the camiladsp executable, and must keep it updated if things change. Forgetting to update (or just picking the wrong path in the first place) could mean the version shown is from the wrong executable.

**Comment by bitkeeper** [comment]
Clear lets close this one.
