### ISSUE TITLE
show dbFS value of capture/playback signal

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camillagui#50]
I found the capture/playback signal very useful. I wish you can also list the dbFS value on the right of the meter. 

btw I also wish to see peak value as well --- that really indicates if something is clipping (that requires a backend change as well). 
Of course these settings can be hidden behind a yml settings flag.

**Comment by JWahle** [comment]
> I found the capture/playback signal very useful. I wish you can also list the dbFS value on the right of the meter.

In the `develop` branches of the backend and frontend, I added a setting to show the level in dB.
You can enable this in the gui-config.yaml in the backend.

> btw I also wish to see peak value as well --- that really indicates if something is clipping (that requires a backend change as well).
Of course these settings can be hidden behind a yml settings flag.

@HEnquist do we really need a setting for this, or should we just use the peak value instead of the rms value?
Does the rms value offer any benefit over the peak value?

**Comment by HEnquist** [comment]
At the moment the VU meter can only show one value, and then I think RMS makes more sense than peak. But I would like to extend it to show both. I have something like this in mind: https://sch-remote.com/pimg/EVOR02x_1.jpg
The rms would then be shown by the full bar, same as now. And the marker to the left shows the peak. It should show the peak from the last few seconds, and not just the instant value.

**Comment by JWahle** [comment]
I implemented something similar - without the labels.
![VU meters](https://user-images.githubusercontent.com/7657699/156063231-6e97e002-90eb-45cf-9a34-7d8e16172dd9.png)

In the backend, I use the peak values from `CamillaConnection.get_capture_signal_peak()` and `CamillaConnection.get_playback_signal_peak()`.

**Comment by JWahle** [comment]
![VuMeters](https://user-images.githubusercontent.com/7657699/158027464-9421f5b7-b1b7-4e85-a6c7-2bdb7815a6f2.png)
How about this?
I left 10% of the bar to indicate clipping.
The steps on the scale are pretty big, due to the 100dB volume range. Should we reduce it?

**Comment by HEnquist** [comment]
Looks really good! The range became 100dB mostly because it's a simple number. We can certainly reduce it. Is 50dB better? Or should it be adjustable via the GUI settings?

**Comment by JWahle** [comment]
> Is 50dB better? Or should it be adjustable via the GUI settings?

For the sake of simplicity, I would go with ~50dB fixed. (I actually went for 51dB, so the minus sign before the "-48" dB label doesn't get truncated.)
Otherwise, I would have to invent some clever logic regarding the dB-labels on the scale. If someone files a bug and gives a good reason, why he needs more, I might be willing to implement it, though.

I think, this looks pretty good:
![VuMeter2](https://user-images.githubusercontent.com/7657699/158075768-0f1c7d2f-b015-4f86-9e75-93692dade291.png)
I tried to get a less pixelated look - to no avail.
Any other remarks? Feel free to be picky ;)

**Comment by HEnquist** [comment]
Yes automatic handling of the scale labels becomes a fair bit of work. I think fixed 50 dB should be fine. 
BTW how would it look if we skip the dB scale numbers between channels, and just have them under the last one?

**Comment by JWahle** [comment]
Labels only at bottom:
![VuMeters labels only bottom](https://user-images.githubusercontent.com/7657699/158079155-9daa7dd5-625b-4c99-b90f-cc38ef1ef096.png)

Labels at top and bottom:
![VuMeters labels top and bottom](https://user-images.githubusercontent.com/7657699/158079261-e039958d-be2f-4def-859b-09c1d6810272.png)

I find it a little hard to read with the labels only at the bottom, but top and bottom looks good to me.

Here is also a comparison of labels between meters and labels only at top and bottom with 2 in and 8 out channels:
![VuMeters 2-8 labels top and bottom](https://user-images.githubusercontent.com/7657699/158079751-64ed54cc-d449-44c9-99b0-587779513fef.png)
![VuMeters 2-8 middle labels](https://user-images.githubusercontent.com/7657699/158079752-d197418b-9b45-421d-9fe2-bf2e5b9ed49f.png)

I like the top and bottom solution the most.
What do you think?

**Comment by JWahle** [comment]
The top/bottom solution is the one currently pushed to `develop`.
If you have any remarks, feel free to reopen the issue.

**Comment by HEnquist** [comment]
Sorry forgot to answer! I agree, top and bottoms looks best.
